import Foundation

// Generated by scripts/generate_who_tables.py from the WHO Child Growth Standards
// (weight-for-age, length-for-age, head-circumference-for-age; months 0-24).
// Do not edit by hand - re-run the script instead.

enum WHOGrowthStandards {

    static func weight(_ sex: BabySex) -> [WHOPoint] {
        sex == .boy ? boysWeight : girlsWeight
    }

    static func height(_ sex: BabySex) -> [WHOPoint] {
        sex == .boy ? boysHeight : girlsHeight
    }

    static func head(_ sex: BabySex) -> [WHOPoint] {
        sex == .boy ? boysHead : girlsHead
    }

    private static let boysWeight: [WHOPoint] = [
        WHOPoint(month:  0, p3:   2.5, p15:   2.9, p50:   3.3, p85:   3.9, p97:   4.3),
        WHOPoint(month:  1, p3:   3.4, p15:   3.9, p50:   4.5, p85:   5.1, p97:   5.7),
        WHOPoint(month:  2, p3:   4.4, p15:   4.9, p50:   5.6, p85:   6.3, p97:   7.0),
        WHOPoint(month:  3, p3:   5.1, p15:   5.6, p50:   6.4, p85:   7.2, p97:   7.9),
        WHOPoint(month:  4, p3:   5.6, p15:   6.2, p50:   7.0, p85:   7.9, p97:   8.6),
        WHOPoint(month:  5, p3:   6.1, p15:   6.7, p50:   7.5, p85:   8.4, p97:   9.2),
        WHOPoint(month:  6, p3:   6.4, p15:   7.1, p50:   7.9, p85:   8.9, p97:   9.7),
        WHOPoint(month:  7, p3:   6.7, p15:   7.4, p50:   8.3, p85:   9.3, p97:  10.2),
        WHOPoint(month:  8, p3:   7.0, p15:   7.7, p50:   8.6, p85:   9.6, p97:  10.5),
        WHOPoint(month:  9, p3:   7.2, p15:   7.9, p50:   8.9, p85:  10.0, p97:  10.9),
        WHOPoint(month: 10, p3:   7.5, p15:   8.2, p50:   9.2, p85:  10.3, p97:  11.2),
        WHOPoint(month: 11, p3:   7.7, p15:   8.4, p50:   9.4, p85:  10.5, p97:  11.5),
        WHOPoint(month: 12, p3:   7.8, p15:   8.6, p50:   9.6, p85:  10.8, p97:  11.8),
        WHOPoint(month: 13, p3:   8.0, p15:   8.8, p50:   9.9, p85:  11.1, p97:  12.1),
        WHOPoint(month: 14, p3:   8.2, p15:   9.0, p50:  10.1, p85:  11.3, p97:  12.4),
        WHOPoint(month: 15, p3:   8.4, p15:   9.2, p50:  10.3, p85:  11.6, p97:  12.7),
        WHOPoint(month: 16, p3:   8.5, p15:   9.4, p50:  10.5, p85:  11.8, p97:  12.9),
        WHOPoint(month: 17, p3:   8.7, p15:   9.6, p50:  10.7, p85:  12.0, p97:  13.2),
        WHOPoint(month: 18, p3:   8.9, p15:   9.7, p50:  10.9, p85:  12.3, p97:  13.5),
        WHOPoint(month: 19, p3:   9.0, p15:   9.9, p50:  11.1, p85:  12.5, p97:  13.7),
        WHOPoint(month: 20, p3:   9.2, p15:  10.1, p50:  11.3, p85:  12.7, p97:  14.0),
        WHOPoint(month: 21, p3:   9.3, p15:  10.3, p50:  11.5, p85:  13.0, p97:  14.3),
        WHOPoint(month: 22, p3:   9.5, p15:  10.5, p50:  11.8, p85:  13.2, p97:  14.5),
        WHOPoint(month: 23, p3:   9.7, p15:  10.6, p50:  12.0, p85:  13.4, p97:  14.8),
        WHOPoint(month: 24, p3:   9.8, p15:  10.8, p50:  12.2, p85:  13.7, p97:  15.1),
    ]

    private static let girlsWeight: [WHOPoint] = [
        WHOPoint(month:  0, p3:   2.4, p15:   2.8, p50:   3.2, p85:   3.7, p97:   4.2),
        WHOPoint(month:  1, p3:   3.2, p15:   3.6, p50:   4.2, p85:   4.8, p97:   5.4),
        WHOPoint(month:  2, p3:   4.0, p15:   4.5, p50:   5.1, p85:   5.9, p97:   6.5),
        WHOPoint(month:  3, p3:   4.6, p15:   5.1, p50:   5.8, p85:   6.7, p97:   7.4),
        WHOPoint(month:  4, p3:   5.1, p15:   5.6, p50:   6.4, p85:   7.3, p97:   8.1),
        WHOPoint(month:  5, p3:   5.5, p15:   6.1, p50:   6.9, p85:   7.8, p97:   8.7),
        WHOPoint(month:  6, p3:   5.8, p15:   6.4, p50:   7.3, p85:   8.3, p97:   9.2),
        WHOPoint(month:  7, p3:   6.1, p15:   6.7, p50:   7.6, p85:   8.7, p97:   9.6),
        WHOPoint(month:  8, p3:   6.3, p15:   7.0, p50:   7.9, p85:   9.0, p97:  10.0),
        WHOPoint(month:  9, p3:   6.6, p15:   7.3, p50:   8.2, p85:   9.3, p97:  10.4),
        WHOPoint(month: 10, p3:   6.8, p15:   7.5, p50:   8.5, p85:   9.6, p97:  10.7),
        WHOPoint(month: 11, p3:   7.0, p15:   7.7, p50:   8.7, p85:   9.9, p97:  11.0),
        WHOPoint(month: 12, p3:   7.1, p15:   7.9, p50:   8.9, p85:  10.2, p97:  11.3),
        WHOPoint(month: 13, p3:   7.3, p15:   8.1, p50:   9.2, p85:  10.4, p97:  11.6),
        WHOPoint(month: 14, p3:   7.5, p15:   8.3, p50:   9.4, p85:  10.7, p97:  11.9),
        WHOPoint(month: 15, p3:   7.7, p15:   8.5, p50:   9.6, p85:  10.9, p97:  12.2),
        WHOPoint(month: 16, p3:   7.8, p15:   8.7, p50:   9.8, p85:  11.2, p97:  12.5),
        WHOPoint(month: 17, p3:   8.0, p15:   8.8, p50:  10.0, p85:  11.4, p97:  12.7),
        WHOPoint(month: 18, p3:   8.2, p15:   9.0, p50:  10.2, p85:  11.6, p97:  13.0),
        WHOPoint(month: 19, p3:   8.3, p15:   9.2, p50:  10.4, p85:  11.9, p97:  13.3),
        WHOPoint(month: 20, p3:   8.5, p15:   9.4, p50:  10.6, p85:  12.1, p97:  13.5),
        WHOPoint(month: 21, p3:   8.7, p15:   9.6, p50:  10.9, p85:  12.4, p97:  13.8),
        WHOPoint(month: 22, p3:   8.8, p15:   9.8, p50:  11.1, p85:  12.6, p97:  14.1),
        WHOPoint(month: 23, p3:   9.0, p15:   9.9, p50:  11.3, p85:  12.8, p97:  14.3),
        WHOPoint(month: 24, p3:   9.2, p15:  10.1, p50:  11.5, p85:  13.1, p97:  14.6),
    ]

    private static let boysHeight: [WHOPoint] = [
        WHOPoint(month:  0, p3:  46.3, p15:  47.9, p50:  49.9, p85:  51.8, p97:  53.4),
        WHOPoint(month:  1, p3:  51.1, p15:  52.7, p50:  54.7, p85:  56.7, p97:  58.4),
        WHOPoint(month:  2, p3:  54.7, p15:  56.4, p50:  58.4, p85:  60.5, p97:  62.2),
        WHOPoint(month:  3, p3:  57.6, p15:  59.3, p50:  61.4, p85:  63.5, p97:  65.3),
        WHOPoint(month:  4, p3:  60.0, p15:  61.7, p50:  63.9, p85:  66.0, p97:  67.8),
        WHOPoint(month:  5, p3:  61.9, p15:  63.7, p50:  65.9, p85:  68.1, p97:  69.9),
        WHOPoint(month:  6, p3:  63.6, p15:  65.4, p50:  67.6, p85:  69.8, p97:  71.6),
        WHOPoint(month:  7, p3:  65.1, p15:  66.9, p50:  69.2, p85:  71.4, p97:  73.2),
        WHOPoint(month:  8, p3:  66.5, p15:  68.3, p50:  70.6, p85:  72.9, p97:  74.7),
        WHOPoint(month:  9, p3:  67.7, p15:  69.6, p50:  72.0, p85:  74.3, p97:  76.2),
        WHOPoint(month: 10, p3:  69.0, p15:  70.9, p50:  73.3, p85:  75.6, p97:  77.6),
        WHOPoint(month: 11, p3:  70.2, p15:  72.1, p50:  74.5, p85:  77.0, p97:  78.9),
        WHOPoint(month: 12, p3:  71.3, p15:  73.3, p50:  75.7, p85:  78.2, p97:  80.2),
        WHOPoint(month: 13, p3:  72.4, p15:  74.4, p50:  76.9, p85:  79.4, p97:  81.5),
        WHOPoint(month: 14, p3:  73.4, p15:  75.5, p50:  78.0, p85:  80.6, p97:  82.7),
        WHOPoint(month: 15, p3:  74.4, p15:  76.5, p50:  79.1, p85:  81.8, p97:  83.9),
        WHOPoint(month: 16, p3:  75.4, p15:  77.5, p50:  80.2, p85:  82.9, p97:  85.1),
        WHOPoint(month: 17, p3:  76.3, p15:  78.5, p50:  81.2, p85:  84.0, p97:  86.2),
        WHOPoint(month: 18, p3:  77.2, p15:  79.5, p50:  82.3, p85:  85.1, p97:  87.3),
        WHOPoint(month: 19, p3:  78.1, p15:  80.4, p50:  83.2, p85:  86.1, p97:  88.4),
        WHOPoint(month: 20, p3:  78.9, p15:  81.3, p50:  84.2, p85:  87.1, p97:  89.5),
        WHOPoint(month: 21, p3:  79.7, p15:  82.2, p50:  85.1, p85:  88.1, p97:  90.5),
        WHOPoint(month: 22, p3:  80.5, p15:  83.0, p50:  86.0, p85:  89.1, p97:  91.6),
        WHOPoint(month: 23, p3:  81.3, p15:  83.8, p50:  86.9, p85:  90.0, p97:  92.6),
        WHOPoint(month: 24, p3:  82.1, p15:  84.6, p50:  87.8, p85:  91.0, p97:  93.6),
    ]

    private static let girlsHeight: [WHOPoint] = [
        WHOPoint(month:  0, p3:  45.6, p15:  47.2, p50:  49.1, p85:  51.1, p97:  52.7),
        WHOPoint(month:  1, p3:  50.0, p15:  51.7, p50:  53.7, p85:  55.7, p97:  57.4),
        WHOPoint(month:  2, p3:  53.2, p15:  55.0, p50:  57.1, p85:  59.2, p97:  60.9),
        WHOPoint(month:  3, p3:  55.8, p15:  57.6, p50:  59.8, p85:  62.0, p97:  63.8),
        WHOPoint(month:  4, p3:  58.0, p15:  59.8, p50:  62.1, p85:  64.3, p97:  66.2),
        WHOPoint(month:  5, p3:  59.9, p15:  61.7, p50:  64.0, p85:  66.3, p97:  68.2),
        WHOPoint(month:  6, p3:  61.5, p15:  63.4, p50:  65.7, p85:  68.1, p97:  70.0),
        WHOPoint(month:  7, p3:  62.9, p15:  64.9, p50:  67.3, p85:  69.7, p97:  71.6),
        WHOPoint(month:  8, p3:  64.3, p15:  66.3, p50:  68.7, p85:  71.2, p97:  73.2),
        WHOPoint(month:  9, p3:  65.6, p15:  67.6, p50:  70.1, p85:  72.6, p97:  74.7),
        WHOPoint(month: 10, p3:  66.8, p15:  68.9, p50:  71.5, p85:  74.0, p97:  76.1),
        WHOPoint(month: 11, p3:  68.0, p15:  70.2, p50:  72.8, p85:  75.4, p97:  77.5),
        WHOPoint(month: 12, p3:  69.2, p15:  71.3, p50:  74.0, p85:  76.7, p97:  78.9),
        WHOPoint(month: 13, p3:  70.3, p15:  72.5, p50:  75.2, p85:  77.9, p97:  80.2),
        WHOPoint(month: 14, p3:  71.3, p15:  73.6, p50:  76.4, p85:  79.2, p97:  81.4),
        WHOPoint(month: 15, p3:  72.4, p15:  74.7, p50:  77.5, p85:  80.3, p97:  82.7),
        WHOPoint(month: 16, p3:  73.3, p15:  75.7, p50:  78.6, p85:  81.5, p97:  83.9),
        WHOPoint(month: 17, p3:  74.3, p15:  76.7, p50:  79.7, p85:  82.6, p97:  85.0),
        WHOPoint(month: 18, p3:  75.2, p15:  77.7, p50:  80.7, p85:  83.7, p97:  86.2),
        WHOPoint(month: 19, p3:  76.2, p15:  78.7, p50:  81.7, p85:  84.8, p97:  87.3),
        WHOPoint(month: 20, p3:  77.0, p15:  79.6, p50:  82.7, p85:  85.8, p97:  88.4),
        WHOPoint(month: 21, p3:  77.9, p15:  80.5, p50:  83.7, p85:  86.8, p97:  89.4),
        WHOPoint(month: 22, p3:  78.7, p15:  81.4, p50:  84.6, p85:  87.8, p97:  90.5),
        WHOPoint(month: 23, p3:  79.6, p15:  82.2, p50:  85.5, p85:  88.8, p97:  91.5),
        WHOPoint(month: 24, p3:  80.3, p15:  83.1, p50:  86.4, p85:  89.8, p97:  92.5),
    ]

    private static let boysHead: [WHOPoint] = [
        WHOPoint(month:  0, p3:  32.1, p15:  33.1, p50:  34.5, p85:  35.8, p97:  36.9),
        WHOPoint(month:  1, p3:  35.1, p15:  36.1, p50:  37.3, p85:  38.5, p97:  39.5),
        WHOPoint(month:  2, p3:  36.9, p15:  37.9, p50:  39.1, p85:  40.3, p97:  41.3),
        WHOPoint(month:  3, p3:  38.3, p15:  39.3, p50:  40.5, p85:  41.7, p97:  42.7),
        WHOPoint(month:  4, p3:  39.4, p15:  40.4, p50:  41.6, p85:  42.9, p97:  43.9),
        WHOPoint(month:  5, p3:  40.3, p15:  41.3, p50:  42.6, p85:  43.8, p97:  44.8),
        WHOPoint(month:  6, p3:  41.0, p15:  42.1, p50:  43.3, p85:  44.6, p97:  45.6),
        WHOPoint(month:  7, p3:  41.7, p15:  42.7, p50:  44.0, p85:  45.3, p97:  46.3),
        WHOPoint(month:  8, p3:  42.2, p15:  43.2, p50:  44.5, p85:  45.8, p97:  46.9),
        WHOPoint(month:  9, p3:  42.6, p15:  43.7, p50:  45.0, p85:  46.3, p97:  47.4),
        WHOPoint(month: 10, p3:  43.0, p15:  44.1, p50:  45.4, p85:  46.7, p97:  47.8),
        WHOPoint(month: 11, p3:  43.4, p15:  44.4, p50:  45.8, p85:  47.1, p97:  48.2),
        WHOPoint(month: 12, p3:  43.6, p15:  44.7, p50:  46.1, p85:  47.4, p97:  48.5),
        WHOPoint(month: 13, p3:  43.9, p15:  45.0, p50:  46.3, p85:  47.7, p97:  48.8),
        WHOPoint(month: 14, p3:  44.1, p15:  45.2, p50:  46.6, p85:  47.9, p97:  49.0),
        WHOPoint(month: 15, p3:  44.3, p15:  45.5, p50:  46.8, p85:  48.2, p97:  49.3),
        WHOPoint(month: 16, p3:  44.5, p15:  45.6, p50:  47.0, p85:  48.4, p97:  49.5),
        WHOPoint(month: 17, p3:  44.7, p15:  45.8, p50:  47.2, p85:  48.6, p97:  49.7),
        WHOPoint(month: 18, p3:  44.9, p15:  46.0, p50:  47.4, p85:  48.7, p97:  49.9),
        WHOPoint(month: 19, p3:  45.0, p15:  46.2, p50:  47.5, p85:  48.9, p97:  50.0),
        WHOPoint(month: 20, p3:  45.2, p15:  46.3, p50:  47.7, p85:  49.1, p97:  50.2),
        WHOPoint(month: 21, p3:  45.3, p15:  46.4, p50:  47.8, p85:  49.2, p97:  50.4),
        WHOPoint(month: 22, p3:  45.4, p15:  46.6, p50:  48.0, p85:  49.4, p97:  50.5),
        WHOPoint(month: 23, p3:  45.6, p15:  46.7, p50:  48.1, p85:  49.5, p97:  50.7),
        WHOPoint(month: 24, p3:  45.7, p15:  46.8, p50:  48.3, p85:  49.7, p97:  50.8),
    ]

    private static let girlsHead: [WHOPoint] = [
        WHOPoint(month:  0, p3:  31.7, p15:  32.7, p50:  33.9, p85:  35.1, p97:  36.1),
        WHOPoint(month:  1, p3:  34.3, p15:  35.3, p50:  36.5, p85:  37.8, p97:  38.8),
        WHOPoint(month:  2, p3:  36.0, p15:  37.0, p50:  38.3, p85:  39.5, p97:  40.5),
        WHOPoint(month:  3, p3:  37.2, p15:  38.2, p50:  39.5, p85:  40.8, p97:  41.9),
        WHOPoint(month:  4, p3:  38.2, p15:  39.3, p50:  40.6, p85:  41.9, p97:  43.0),
        WHOPoint(month:  5, p3:  39.0, p15:  40.1, p50:  41.5, p85:  42.8, p97:  43.9),
        WHOPoint(month:  6, p3:  39.7, p15:  40.8, p50:  42.2, p85:  43.5, p97:  44.6),
        WHOPoint(month:  7, p3:  40.4, p15:  41.5, p50:  42.8, p85:  44.2, p97:  45.3),
        WHOPoint(month:  8, p3:  40.9, p15:  42.0, p50:  43.4, p85:  44.7, p97:  45.9),
        WHOPoint(month:  9, p3:  41.3, p15:  42.4, p50:  43.8, p85:  45.2, p97:  46.3),
        WHOPoint(month: 10, p3:  41.7, p15:  42.8, p50:  44.2, p85:  45.6, p97:  46.8),
        WHOPoint(month: 11, p3:  42.0, p15:  43.2, p50:  44.6, p85:  46.0, p97:  47.1),
        WHOPoint(month: 12, p3:  42.3, p15:  43.5, p50:  44.9, p85:  46.3, p97:  47.5),
        WHOPoint(month: 13, p3:  42.6, p15:  43.8, p50:  45.2, p85:  46.6, p97:  47.7),
        WHOPoint(month: 14, p3:  42.9, p15:  44.0, p50:  45.4, p85:  46.8, p97:  48.0),
        WHOPoint(month: 15, p3:  43.1, p15:  44.2, p50:  45.7, p85:  47.1, p97:  48.2),
        WHOPoint(month: 16, p3:  43.3, p15:  44.4, p50:  45.9, p85:  47.3, p97:  48.5),
        WHOPoint(month: 17, p3:  43.5, p15:  44.6, p50:  46.1, p85:  47.5, p97:  48.7),
        WHOPoint(month: 18, p3:  43.6, p15:  44.8, p50:  46.2, p85:  47.7, p97:  48.8),
        WHOPoint(month: 19, p3:  43.8, p15:  45.0, p50:  46.4, p85:  47.8, p97:  49.0),
        WHOPoint(month: 20, p3:  44.0, p15:  45.1, p50:  46.6, p85:  48.0, p97:  49.2),
        WHOPoint(month: 21, p3:  44.1, p15:  45.3, p50:  46.7, p85:  48.2, p97:  49.4),
        WHOPoint(month: 22, p3:  44.3, p15:  45.4, p50:  46.9, p85:  48.3, p97:  49.5),
        WHOPoint(month: 23, p3:  44.4, p15:  45.6, p50:  47.0, p85:  48.5, p97:  49.7),
        WHOPoint(month: 24, p3:  44.6, p15:  45.7, p50:  47.2, p85:  48.6, p97:  49.8),
    ]
}
